USE CALL_CENTER
SELECT * FROM CALL_CENTERS

-- CAMBIANDO EL MODELO DE RECUPERACION ---
USE master
ALTER DATABASE CALL_CENTER SET RECOVERY SIMPLE

-- BACKUP MANUAL DE LA BASE DE DATOS ---
BACKUP DATABASE "CALL_CENTER"
TO DISK = 'C:\BACKUP1103.BAK'

BACKUP DATABASE CALL_CENTER
TO DISK = 'C:\BACKUP1250AM17012012.bak'

-- BACKUP LOG
BACKUP LOG "CALL_CENTER"
TO DISK = 'C:\BACKUP1103.BAK'
WITH NORECOVERY

-- RESTAURACION MANUAL DE LA BASE DE DATOS --
RESTORE DATABASE "CALL_CENTER"
FROM DISK = 'C:\BACKUP1103.BAK'
WITH FILE = 1,
REPLACE;

-- BORRAR LOS DATOS DE UNA TABLA ESPECIFICA EN LA BASE DE DATOS --
USE CALL_CENTER
DELETE FROM CALL_CENTERS
GO
-- RESTAURAR LOG
RESTORE log PARCIAL3
FROM DISK = 'C:\BACKUP\tony3.bak'
WITH RECOVERY

-- COMANDOS BCP GUIA 13 
-----------------IMPORTAR DATOS A TABLAS ---------------
-- ESTRUCTURA: BCP [nombre_de_la_base].[nombre_objeto].[nombre_tabla] IN [ubicacion_archivo] 
-- -S[nombre_servidor\nombre_instancia] -U[nombre_cuenta_usuario] -P[contraseña_cuenta]

-- NOTA: SE USA -c para modo caracter(cuando se exportan datos a otras bases que no son
-- SQL Server, aunq no es exclusivo para otras bases). Se puede usar -n para modo nativo. 

-- BCP CALL_CENTER.dbo.CALL_CENTERS IN C:\CALLCENTER.dat -c -STONY-PC\GC06016 -Usa -PSQLServer2012
-- BCP CALL_CENTER.dbo.COMMON_PROBLEMS IN C:\COMMON_PROBLEMS.dat -c -STONY-PC\GC06016 -Usa -PSQLserver2012
-- BCP CALL_CENTER.dbo.COMMON_SOLUTIONS IN C:\COMMON_SOLUTIONS.dat -STONY-PC\GC06016 -Usa -PSQLServer2012
-- BCP CALL_CENTER.dbo.CONTRACTS IN C:\CONTRACTS.dat -c -STONY-PC\GC06016 -Usa -PSQLServer2012


------------- EXPORTAR DATOS DE TABLAS ----------------
-- BCP CALL_CENTER.dbo.CALL_CENTER OUT C:\CALLCENTER.dat -c -SONY-PC\GC06016 -Usa -PSQLServer