SELECT TO_DATE(SYSDATE) FROM DUAL;
SELECT TO_CHAR(TO_DATE(SYSDATE)) FROM DUAL;
SELECT SUBSTR(TO_CHAR(TO_DATE(SYSDATE)),4,2) FROM DUAL;
SELECT TO_NUMBER(SUBSTR(TO_CHAR(TO_DATE(SYSDATE)),4,2)) FROM DUAL;
SELECT TO_NUMBER(SUBSTR(TO_CHAR(TO_DATE(SYSDATE)),7,2)) FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;

SELECT DECODE(a.dia,
			  TO_CHAR(SYSDATE,'DD/MM/YYYY'), 'hoy',
			  'otro dia') fecha
  FROM (SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY') dia FROM dual) a;
/*
FECHA
--------
hoy     
1 row selected.
*/
SELECT DECODE(a.dia,
			  SYSDATE, 'hoy',
			  'otro dia') fecha
  FROM (SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY') dia FROM dual) a;
/*
FECHA
--------
otro dia
1 row selected.
*/