LOAD DATA INFILE data
    INTO TABLE SALES
    INSERT
    FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '^'
(PROD_ID,
 CUST_ID,
 TIME_ID DATE(10) "YYYY-MM-DD",
 CHANNEL_ID,
 PROMO_ID,
 QUANTITY_SOLD,
 AMOUNT_SOLD)
