::*****************************
::*Ejecutar como Administrador
::*****************************

F:\setup.exe /ACTION=INSTALL /QS /FEATURES=SQL,AS,RS,IS,TOOLS,BIDS,BOL /INDICATEPROGRESS /INSTANCENAME="CG06009" /SECURITYMODE="SQL" /SAPWD="12345" /SQLSYSADMINACCOUNTS="M11x\Neotaku"  /SQLSVCACCOUNT="Neotaku" /SQLSVCPASSWORD="12345" /AGTSVCACCOUNT="Neotaku" /AGTSVCPASSWORD="12345" /ASSYSADMINACCOUNTS="M11x\Neotaku" /ASSVCACCOUNT="Neotaku" /ASSVCPASSWORD="12345" /RSSVCACCOUNT="M11x\Neotaku" /RSSVCPASSWORD="12345" /ISSVCACCOUNT="NT AUTHORITY\NETWORK SERVICE"