USE PARCIAL3
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER tr_insert_MiExamenMG04077
	ON DATABASE
	FOR CREATE_TABLE
AS
BEGIN
    EXEC sp_insert_MiExamenMG04077 1000
END /*fin tr_insert_MiExamenMG04077*/